name: Generate Spotify Track Image

on:
  # This allows you to run the action manually from the Actions tab
  workflow_dispatch:
  # This runs the action automatically once a week to keep the image fresh
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: kittinan/spotify-github-profile@v1.1.0
        with:
          # This is the Spotify track ID for "Evol - Sofia Anessiadis"
          TRACK_ID: '1vjHrH48y26d852g3c7aPq'
          # This is the name of the file it will create in your repository
          OUTPUT_PATH: 'spotify-track.svg'
